### PR TITLE
Fix extension examples empty-state messaging

### LINKED ISSUE #184: Distinguish empty state for extension examples when not found vs when not available
Currently when you type in a string which matches no examples it will ask you to pull extension examples submodule which is not appropriate in 99% use case:

Image

### PR DESCRIPTION
**Pull request by MUFFANUJ**
Fixes #184 

This PR improves extension examples' empty-state behaviour and messaging by distinguishing filter no-match results from true example unavailability.

### CODE REVIEW

File: src/example-sidebar.tsx [hunk 1]
```diff
@@ -102,23 +108,31 @@ export class ExampleSidebar extends ReactWidget {
...
         ) : null}
-        {!this._isLoading &&
-        !this._errorMessage &&
-        filteredExamples.length === 0 ? (
-          <div>
-            <p className="jp-PluginPlayground-count">
-              No extension examples found in <code>extension-examples/</code>.
+        {hasNoMatchingExamples ? (
+          <p className="jp-PluginPlayground-count">
+            No matching extension examples Found.
```
Comment (krassowski) [inline src/example-sidebar.tsx]:
```suggestion
            No matching extension examples found.
```

**Review by krassowski — APPROVED** [review]
Just one typo
